name: 'GitHub Action for Hetzner - hcloud'
description: 'Use hcloud to manage your Hetzner cloud resources.'
author: 'techknowlogick <techknowlogick@gitea.io>'
inputs:
  version:
    description: 'Version of hcloud to install'
    default: 'latest'
  token:
    description: 'Hetzner API Key'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'